- name: Configure Web and DB servers
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Create a custom index.html
      copy:
        content: "<h1>Hello from {{ ansible_hostname }}! Deployed via TF + Ansible</h1>"
        dest: /var/www/html/index.html
